### ISSUE TITLE
Tags with undersore in middle not rendering with same color

### ISSUE THREAD

**Issue by icebruce** [pfrankov/obsidian-colored-tags#20]
Because you cant use a space between multi word tags, you need to use pascal case, camel case etc. 
When using underscore to break a multi word tag, the tags uses two colors

**Comment by pfrankov** [comment]
Thank you for the report! It seems that you found an another limitation of the plugin: Obsidian itself breaks tags by underscore `_`
<img width="358" alt="test/test_nest" src="https://github.com/pfrankov/obsidian-colored-tags/assets/584632/f1c874c6-d930-4a78-ac35-80a8e1ff8fc8">  
So instead of one `test/test_nest` tag it's two now: `test/test_` and `nest`.

Use camelCase if you need to split words.
