### ISSUE TITLE
Tags for YAML format do not work

### ISSUE THREAD

**Issue by csdjk** [pfrankov/obsidian-colored-tags#21]
![image](https://github.com/pfrankov/obsidian-colored-tags/assets/33519787/47dc5b45-6321-4e38-b746-d85a8039575e)

**Comment by pfrankov** [comment]
As described in Limitations:
<img width="517" alt="Properties tags can not be styled until fixes in Obsidian" src="https://github.com/pfrankov/obsidian-colored-tags/assets/584632/cdffcfa6-d2d5-47da-8bf8-4c1a3a116462">
It's not possible for now because there is no way to distinguish one tag from another.

Since this is the third mention of the same limitation, I will leave this issue open.

**Comment by Shreshth-mehra** [comment]
I'd like this too. I prefer having tags only in the YAML property but want them coloured
