### ISSUE TITLE
Analogous Hues

### ISSUE THREAD

**Issue by 8itlew7r** [pfrankov/obsidian-colored-tags#25]
Hello, I need to assign a large number of tags to words/phrases to identify connections. However, I've encountered an issue where the colors assigned to different tags sometimes appear very similar to the human eye, even if they are technically distinct in a digital sense.

A potential solution to minimize the likelihood of similar colors for tags is to introduce an option that supports the use of multiple palettes: one for adaptive soft themes and another for adaptive bright themes. Additionally, for tags with similar hues (e.g., various shades of blue), provide an option to automatically differentiate the text color from that of tags with analogous hues, ensuring visual distinctness between them.

![problem_sample](https://github.com/user-attachments/assets/afbd1cb4-21f3-45a1-8dcb-84d92d8919db)

**Comment by pfrankov** [comment]
If I understand correctly you're asking to provide more distinct colors in palettes. The problem is they are already most visually distinct colors of the same lightness. I've tried to use different lightness and saturation to increase the number of variations but in the result I cannot say that the tags back-to-back are very appealing. But I agree that the 8'th color is on the edge of recognition. Probably it should be 5-6 colors in the default palettes but I'll leave 8 because it will be painful to update on this version.

The easiest way to solve your problem is Custom palette and https://medialab.github.io/iwanthue/
Play with numbers like so:
```
c64b8d-8ed849-8c40cb-75c080-7d78c1-c8ae50-4c2d4a-7bb9bf-c15238-525734-cb9ca0
```

**Comment by 8itlew7r** [comment]
I apologize for my limited knowledge of colors and design principles, as my current approach is likely impractical and cumbersome. What I really need is to think more creatively and develop a more organized method to effectively connect the dots in terms of color coordination.

Thank you for the helpful suggestion! I utilized the website you shared and created a color palette of 100 shades, which has significantly improved the outcome."

```
5776b6-aec532-3c66e8-6eb62c-7951d0-52c953-9b40b5-43b85d-e459c2-42942c-d26ee2-40d18a-da3995-89c45e-a974ee-7d9a28-4553c2-b7b43e-3770df-dcae3f-7048b1-e4912d-7d76e4-df651e-638ced-b94414-66cbf6-c23223-59ceb5-e73379-348f50-a83297-34752d-955fc0-507522-5c51b1-a38f36-4769c1-ee5d3f-2baad3-e43450-47b083-c9294d-3fbdc6-b4323a-7cc283-6e4197-737921-b188e4-4b600e-e670b4-296437-af367e-799b51-785bae-b47e27-5597e1-e98551-275ba0-ab5f23-57a7de-f0685e-33957d-d84b7b-1a6447-e45d6a-2f7b63-af325a-508a5a-bb66b2-415a1f-de96de-5b5b10-7875c2-78641b-505099-b7b771-86458a-597236-a4a3e5-903f1d-4585b3-b85138-505b8f-e4aa78-815c97-62612c-a97fbd-86602b-e97292-89834d-894061-bc8754-aa5d81-895029-e18fb0-ad644a-99454c-ea8b78-c66e70
```
