### ISSUE TITLE
Any chance this plugin could work with tags in the new Properties fields

### ISSUE THREAD

**Issue by obvionaoe** [pfrankov/obsidian-colored-tags#8]
Basically what the title says :smile: 

Thanks for your work on this useful plugin!

**Comment by pfrankov** [comment]
Thank you for your interest in improvement this plugin!
As it is written in Limitations in README.md, it's not possible for now because there is no way to distinguish one tag from another.
<img width="528" alt="image" src="https://github.com/pfrankov/obsidian-colored-tags/assets/584632/3a12f121-57b7-405d-a494-3ef7076a75d6">
